import type { Candidate, CandidateValue, Criterion, CriterionType, DecisionScenario, EnumCriterion, EnumOption } from "./types";
export declare function createId(prefix?: string): string;
export declare function clamp(value: number, min: number, max: number): number;
export declare function createCandidate(name?: string): Candidate;
export declare function createCriterion(type?: CriterionType): Criterion;
export declare function getDefaultValueForCriterion(criterion: Criterion): CandidateValue;
export declare function convertCriterionType(criterion: Criterion, nextType: CriterionType): Criterion;
export declare function cloneCandidate(candidate: Candidate): Candidate;
export declare function syncScenario(scenario: DecisionScenario): DecisionScenario;
export declare function touchScenario(scenario: DecisionScenario): DecisionScenario;
export declare function createEmptyScenario(): DecisionScenario;
export declare function createScenarioFromSeed(seed: Omit<DecisionScenario, "id" | "createdAt" | "updatedAt">): DecisionScenario;
export declare function formatNumber(value: number): string;
export declare function updateEnumOptionLabels(criterion: EnumCriterion, nextOptions: EnumOption[]): EnumCriterion;
